table 'Sales history and forecast'
	lineageTag: 49752339-bc51-494c-9071-cac701505ad3

	column InvoiceDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6762f354-8915-4ecd-8ab4-944ef56ea834
		summarizeBy: none
		sourceColumn: InvoiceDate

		variation Variation
			isDefault
			relationship: 763bb982-c421-40b8-8b38-be098ee4a012
			defaultHierarchy: LocalDateTable_0c2f76a0-79b5-4bd0-995a-0cd4d56f656b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VehicleTypeShort
		dataType: string
		lineageTag: 5ec76679-05d1-4f64-ae7e-1157f3dbf138
		summarizeBy: none
		sourceColumn: VehicleTypeShort

		annotation SummarizationSetBy = Automatic

	column UnitsSold
		dataType: double
		lineageTag: e1595935-e97a-4cf5-ac03-9f77750d52dd
		summarizeBy: sum
		sourceColumn: UnitsSold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ForecastValue
		dataType: int64
		formatString: 0
		lineageTag: 3f38f6f3-3e54-4130-a5ac-16d08da6ca00
		summarizeBy: none
		sourceColumn: ForecastValue

		annotation SummarizationSetBy = Automatic

	partition 'Sales history and forecast' = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Sales Monthly History", #"Sales Forecast"}),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"InvoiceDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

