table 'Sales Forecast'
	lineageTag: 921956f8-5410-45ae-b35c-89dd5564d7e8

	column InvoiceDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8dcb16f7-fc94-4c29-8f65-5b3327c5b45e
		summarizeBy: none
		sourceColumn: InvoiceDate

		variation Variation
			isDefault
			relationship: 79b3a642-305b-4bb0-97ca-028f4037e3dd
			defaultHierarchy: LocalDateTable_4a6320ee-93ec-41b5-8828-d69ba047a965.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ForecastValue
		dataType: int64
		formatString: 0
		lineageTag: daac5fe2-507a-47e1-a3fe-6eee005851a8
		summarizeBy: none
		sourceColumn: ForecastValue

		annotation SummarizationSetBy = Automatic

	column VehicleTypeShort
		dataType: string
		lineageTag: c9a45ee1-cd5b-4f90-86c6-7ab4f437049f
		summarizeBy: none
		sourceColumn: VehicleTypeShort

		annotation SummarizationSetBy = Automatic

	column UnitsSold
		dataType: int64
		formatString: 0
		lineageTag: 7e8bda6b-6e97-47f1-a34e-13461a21f60b
		summarizeBy: sum
		sourceColumn: UnitsSold

		annotation SummarizationSetBy = Automatic

	partition 'Sales Forecast' = m
		mode: import
		source =
				let
				    Source = Sql.Database("7feayvayvgkebc6l4lr5ck2nkq-c7rf6hb2ej7erc674mjqmjlkeu.datawarehouse.fabric.microsoft.com", "DPMC_Lakehouse_External", [Query="SELECT #(lf)    CONVERT(varchar(10), DATEFROMPARTS(YEAR(S.InvoiceDate), MONTH(S.InvoiceDate), 1), 23) AS InvoiceDate,#(lf)    CASE WHEN P.STR_PRODLINE_DESC = '2 WHEELERS' THEN '2W'#(lf)         WHEN P.STR_PRODLINE_DESC = '3 WHEELERS' THEN '3W' END AS VehicleTypeShort,#(lf)    COUNT(DISTINCT S.ChassisNo) AS UnitsSold#(lf)FROM gold_dpmc_vs_2w3w4w_factsales S#(lf)INNER JOIN gold_dpmc_vs_2w3w4w_dimproduct P ON P.ProductSK = S.ProductSK#(lf)WHERE P.STR_PRODLINE_DESC IN ('2 WHEELERS','3 WHEELERS')#(lf)GROUP BY DATEFROMPARTS(YEAR(S.InvoiceDate), MONTH(S.InvoiceDate), 1),#(lf)         CASE WHEN P.STR_PRODLINE_DESC = '2 WHEELERS' THEN '2W'#(lf)              WHEN P.STR_PRODLINE_DESC = '3 WHEELERS' THEN '3W' END#(lf)ORDER BY 1, 2;"]),
				    #"Run Python script" = Python.Execute("import os#(lf)os.environ['OPENBLAS_NUM_THREADS'] = '1'#(lf)os.environ['OMP_NUM_THREADS'] = '1'#(lf)os.environ['MKL_NUM_THREADS'] = '1'#(lf)#(lf)import pandas as pd#(lf)from statsmodels.tsa.holtwinters import ExponentialSmoothing#(lf)#(lf)raw = dataset.copy()#(lf)raw['InvoiceDate'] = pd.to_datetime(raw['InvoiceDate'])#(lf)#(lf)results = []#(lf)for vt in raw['VehicleTypeShort'].dropna().unique():#(lf)    df = raw[raw['VehicleTypeShort'] == vt].copy()#(lf)    df = df.sort_values('InvoiceDate').drop_duplicates(subset='InvoiceDate', keep='last')#(lf)    df = df.set_index('InvoiceDate')#(lf)    df = df.asfreq('MS')#(lf)#(lf)    today = pd.Timestamp.today().normalize()#(lf)    current_month_start = today.replace(day=1)#(lf)    if len(df) and df.index[-1] >= current_month_start:#(lf)        df = df.iloc[:-1]#(lf)#(lf)    df['UnitsSold'] = df['UnitsSold'].fillna(0)#(lf)#(lf)    has_zero = (df['UnitsSold'] == 0).any()#(lf)    trend_type = 'add' if has_zero else 'mul'#(lf)    seasonal_type = 'add' if has_zero else 'mul'#(lf)#(lf)    use_seasonal = len(df) >= 24#(lf)#(lf)    if use_seasonal:#(lf)        model = ExponentialSmoothing(#(lf)            df['UnitsSold'], trend=trend_type, damped_trend=True,#(lf)            seasonal=seasonal_type, seasonal_periods=12,#(lf)            initialization_method='estimated'#(lf)        )#(lf)    else:#(lf)        model = ExponentialSmoothing(#(lf)            df['UnitsSold'], trend=trend_type, damped_trend=True,#(lf)            seasonal=None,#(lf)            initialization_method='estimated'#(lf)        )#(lf)#(lf)    fitted_model = model.fit(optimized=True)#(lf)    forecast = fitted_model.forecast(steps=3)#(lf)    vt_forecast = pd.DataFrame({'ForecastValue': forecast}).reset_index().rename(columns={'index': 'InvoiceDate'})#(lf)    vt_forecast['VehicleTypeShort'] = vt#(lf)    results.append(vt_forecast)#(lf)#(lf)forecast_df = pd.concat(results, ignore_index=True)#(lf)",[dataset=Source]),
				    forecast_df = #"Run Python script"{[Name="forecast_df"]}[Value],
				    #"Changed Type" = Table.TransformColumnTypes(forecast_df,{{"InvoiceDate", type date}, {"ForecastValue", Int64.Type}, {"VehicleTypeShort", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "UnitsSold", each null),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"UnitsSold", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

